default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_development
  host: localhost
  port: 5432

staging:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_staging
  host: localhost
  port: 5432

test:
  <<: *default
  host: localhost
  database: <%= ENV['DB_NAME'] %>_test
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV['DB_NAME'] %>_staging
